# Generated by Django 2.1.7 on 2019-02-14 03:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('frequency', models.IntegerField(default=10)),
                ('priority', models.IntegerField(default=3)),
                ('next_reminder', models.DateField()),
                ('last_contacted', models.DateField(default=datetime.datetime(2019, 2, 14, 3, 18, 10, 685868))),
                ('notes', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
