# Generated by Django 2.1.7 on 2019-02-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('frequency', models.IntegerField(default=10)),
                ('priority', models.IntegerField(default=3)),
                ('next_reminder', models.DateField(verbose_name=django.utils.timezone.now)),
                ('last_contacted', models.DateField(verbose_name=django.utils.timezone.now)),
                ('notes', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
