# Generated by Django 2.1.7 on 2019-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateField(),
        ),
    ]
