# Generated by Django 2.1.7 on 2019-02-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_contactdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactDetails', to='api_v1.Contact'),
        ),
    ]
