# Generated by Django 2.1.7 on 2019-02-18 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20190217_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='frequency',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='next_reminder',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
